server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://ecommerce-db.cfyiuuqsk69c.us-east-2.rds.amazonaws.com:5432/notificationdb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "com.example.ecommerce.common.event"
      spring.json.value.default.type: "com.example.ecommerce.common.event.OrderPlacedEvent"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
